# Generated by Django 5.2.7 on 2025-11-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMC_classificazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato_nutrizione', models.CharField(max_length=50, unique=True, verbose_name='stato di nutrizione')),
                ('classe_obesita', models.CharField(blank=True, max_length=5, null=True, verbose_name='Classe di Obesità')),
                ('intervallo_imc', models.CharField(max_length=20, verbose_name='IMC(kg/m)')),
            ],
        ),
        migrations.CreateModel(
            name='Obesita_viscerale_Rischio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere', models.CharField(choices=[('Uomini', 'Uomini'), ('Donne', 'Donne')], max_length=10, unique=True, verbose_name='Genere')),
                ('circonferenza_addominale_soglia', models.PositiveSmallIntegerField(verbose_name='Circonferenza Addominale soglia(cm)')),
                ('condizione_rischio', models.CharField(max_length=15, verbose_name='Condizione di Rischio')),
            ],
            options={
                'verbose_name': 'Rischio Obesità Viscerale',
                'verbose_name_plural': 'Rischio Obesità Viscerale',
            },
        ),
    ]
