# Generated by Django 5.2.7 on 2025-11-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcolatore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imc_classificazione',
            options={'verbose_name': 'Classificazione IMC', 'verbose_name_plural': 'Classificazione IMC'},
        ),
    ]
