# Generated by Django 5.2.7 on 2025-11-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcolatore', '0002_alter_imc_classificazione_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obesita_viscerale_rischio',
            name='condizione_rischio',
            field=models.CharField(max_length=20, verbose_name='Condizione di Rischio'),
        ),
    ]
