# Generated by Django 5.2.7 on 2025-12-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcolatore', '0003_alter_obesita_viscerale_rischio_condizione_rischio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabisognoEnergetico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere', models.CharField(choices=[('Uomini', 'Uomini'), ('Donne', 'Donne')], max_length=10, unique=True, verbose_name='Genere')),
                ('classe_eta', models.CharField(max_length=10, verbose_name='classe di età')),
                ('livello_attivita_fisica', models.CharField(max_length=20, verbose_name='livello_attivita_fisica')),
                ('laf', models.FloatField(max_length=10, verbose_name='LAF')),
            ],
            options={
                'verbose_name': ('LAF giornalieri per adulti e anziani',),
                'verbose_name_plural': ('LAF giornalieri per adulti e anzioni',),
            },
        ),
    ]
