# Generated by Django 5.2.7 on 2025-12-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcolatore', '0004_fabisognoenergetico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabisognoenergetico',
            name='genere',
            field=models.CharField(choices=[('Uomini', 'Uomini'), ('Donne', 'Donne')], max_length=10, verbose_name='Genere'),
        ),
    ]
