# Generated by Django 5.2.7 on 2025-12-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcolatore', '0005_alter_fabisognoenergetico_genere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabisognoenergetico',
            name='livello_attivita_fisica',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='livello_attivita_fisica'),
        ),
    ]
