# Generated by Django 5.2.7 on 2025-12-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcolatore', '0006_alter_fabisognoenergetico_livello_attivita_fisica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabisogno_Energetico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere', models.CharField(choices=[('Uomini', 'Uomini'), ('Donne', 'Donne')], max_length=10, verbose_name='Genere')),
                ('classe_eta', models.CharField(max_length=10, verbose_name='classe di età')),
                ('livello_attivita_fisica', models.CharField(blank=True, max_length=20, null=True, verbose_name='livello_attivita_fisica')),
                ('laf', models.FloatField(max_length=10, verbose_name='LAF')),
            ],
            options={
                'verbose_name': ('LAF giornalieri per adulti e anziani',),
                'verbose_name_plural': ('LAF giornalieri per adulti e anzioni',),
            },
        ),
        migrations.CreateModel(
            name='Metabolismo_Basale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta', models.IntegerField(max_length=10, verbose_name='eta')),
                ('genere', models.CharField(choices=[('Uomini', 'Uomini'), ('Donne', 'Donne')], max_length=10, verbose_name='Genere')),
                ('kcal_giorno', models.CharField(max_length=50, verbose_name='kcal/giorno')),
            ],
        ),
        migrations.DeleteModel(
            name='FabisognoEnergetico',
        ),
    ]
