# Generated by Django 5.2.7 on 2025-12-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcolatore', '0007_fabisogno_energetico_metabolismo_basale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metabolismo_basale',
            name='eta',
            field=models.CharField(max_length=10, verbose_name='eta'),
        ),
    ]
