# Generated by Django 5.2.7 on 2025-12-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcolatore', '0008_alter_metabolismo_basale_eta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabisogno_energetico_adolescenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_eta', models.CharField(max_length=10, verbose_name='classe di età')),
                ('genere', models.CharField(choices=[('Maschi', 'Maschi'), ('Femmine', 'Femmine')], max_length=10, verbose_name='Genere')),
                ('laf', models.FloatField(max_length=10, verbose_name='LAF')),
            ],
            options={
                'verbose_name': ('LAF giornalieri per adulti e anziani',),
                'verbose_name_plural': ('LAF giornalieri per adulti e anzioni',),
            },
        ),
        migrations.AlterModelOptions(
            name='metabolismo_basale',
            options={'verbose_name': ('metabolismo basale',), 'verbose_name_plural': ('metabolismo basale',)},
        ),
    ]
