# Generated by Django 5.2.7 on 2025-12-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcolatore', '0009_fabisogno_energetico_adolescenti_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabisogno_energetico_adolescenti',
            options={'verbose_name': ('LAF giornalieri per Adolescenti',), 'verbose_name_plural': ('LAF giornalieri per Adolescenti',)},
        ),
    ]
