# Generated by Django 5.2.7 on 2025-12-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcolatore', '0010_alter_fabisogno_energetico_adolescenti_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabisogno_energetico',
            name='classe_eta',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='classe di età'),
        ),
    ]
