# Generated by Django 5.2.7 on 2025-12-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcolatore', '0011_alter_fabisogno_energetico_classe_eta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabella_Lavori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavoro', models.CharField(max_length=100, unique=True)),
                ('categoria_laf', models.CharField(choices=[('pesante', 'Pesante'), ('moderato', 'Moderato'), ('leggero', 'Leggero')], max_length=20)),
            ],
        ),
    ]
