# Generated by Django 5.2.7 on 2025-12-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcolatore', '0012_tabella_lavori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabella_lavori',
            name='categoria_laf',
            field=models.CharField(choices=[('leggero', 'Leggero'), ('moderato', 'Moderato'), ('pesante', 'Pesante')], max_length=20),
        ),
    ]
