# Generated by Django 5.2.7 on 2025-11-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Codice', models.CharField(blank=True, max_length=100, null=True)),
                ('alimento', models.CharField(blank=True, max_length=200, null=True)),
                ('parte_edibile', models.IntegerField(blank=True, null=True)),
                ('acqua', models.FloatField(blank=True, null=True)),
                ('proteine', models.FloatField(blank=True, null=True)),
                ('lipidi', models.FloatField(blank=True, null=True)),
                ('carboidrati', models.FloatField(blank=True, null=True)),
                ('amido', models.FloatField(blank=True, null=True)),
                ('zuccheri_solubili', models.FloatField(blank=True, null=True)),
                ('fibra_alimentare', models.FloatField(blank=True, null=True)),
                ('energia_kcal', models.IntegerField(blank=True, null=True)),
                ('energia_kj', models.IntegerField(blank=True, null=True)),
                ('sodio', models.FloatField(blank=True, null=True)),
                ('potassio', models.FloatField(blank=True, null=True)),
                ('ferro', models.FloatField(blank=True, null=True)),
                ('calcio', models.FloatField(blank=True, null=True)),
                ('fosforo', models.FloatField(blank=True, null=True)),
                ('tiamina', models.FloatField(blank=True, null=True)),
                ('riboflavina', models.FloatField(blank=True, null=True)),
                ('niacina', models.FloatField(blank=True, null=True)),
                ('vit_a_ret_eg', models.FloatField(blank=True, null=True)),
                ('vitamina_c', models.FloatField(blank=True, null=True)),
                ('vitamina_e', models.FloatField(blank=True, null=True)),
                ('colesterolo', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAlimenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_alimenti', models.CharField(max_length=100)),
            ],
        ),
    ]
