# Generated by Django 5.2.7 on 2025-12-09 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritori', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimenti',
            name='tipo_alimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutritori.tipoalimenti'),
        ),
    ]
